### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by abelass** [ShiraNai7/jquery-scrollwatch#1]
Hi, thanks for the script which works very well.

I have two small issues?

What is the  "use_strict" line for?

The Watcher class has this parameter: 
- @param {Array}    sections array of DOM elements
  but then in line 533 it's initiated with:
  $.fn.scrollWatch = function (callback, options) {
  if (this.length >= 1) {
              var watcher = new ScrollWatch.Watcher(this, callback, options);
  the this will not be an array at that point. This could break the flow of operations.

**Comment by shira-374** [comment]
Hi.

The `"use_strict";` statement enables strict mode in newer JavaScript implementations, [see this article on the MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Strict_mode). It does nothing when not supported.

About `$.fn.scrollWatch` - yes, `this` will be a jQuery object, which is not an actual array but an array-like object.  This is currently not a problem, because only numeric indexes and `.length` are used, but I'll fix it anyway. Nice catch.

**Comment by abelass** [comment]
Ok, thanks for the quick answer

**Comment by shira-374** [comment]
Fixed in 036fbf42
